---
title: "Calibration"
author: "Thomas Klebel"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    keep_md: true
---

```{r setup, include=FALSE}
library(tidyverse)
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, dpi = 300)

theme_set(hrbrthemes::theme_ipsum_rc(base_family = "Hind"))
extrafont::loadfonts(device = "win")

leiden <- targets::tar_read(leiden)
italy <- targets::tar_read(italy)
```


```{r leiden, fig.width=11, fig.height=7}
ginis <- leiden %>% 
  group_by(Period) %>% 
  summarise(gini = ineq::Gini(impact_P),
            label = paste0("Gini = ", round(gini, 3)))

leiden %>% 
  ggplot() +
  geom_histogram(aes(impact_P), binwidth = 2000) +
  facet_wrap(vars(Period)) +
  geom_text(aes(x = 60000, y = 400, label = label), data = ginis) +
  scale_x_continuous(labels = scales::comma) +
  labs(x = "Total number of publications per university", 
       y = "# of universities")
```

Create a version that fits better on the page
```{r leiden-3x3, fig.width=7, fig.height=7}
gini_reduced <- filter(ginis, Period != "2006–2009")

leiden %>% 
  filter(Period != "2006–2009") %>% 
  ggplot() +
  geom_histogram(aes(impact_P), binwidth = 2000) +
  facet_wrap(vars(Period), nrow = 3) +
  geom_text(aes(x = 60000, y = 400, label = label), data = gini_reduced) +
  scale_x_continuous(labels = scales::comma, breaks = c(4e+4, 8e+4)) +
  labs(x = "Total number of publications per university", 
       y = "# of universities")
```

