---
title: "Rational learning"
author: "Thomas Klebel"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    keep_md: true
---

```{r setup, include=FALSE}
library(tidyverse)
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, dpi = 300)

theme_set(hrbrthemes::theme_ipsum_rc(base_family = "Hind"))
extrafont::loadfonts(device = "win")

df <- targets::tar_read(rational)

df_clean <- df %>% 
  filter(.step. >= sharing.start) %>% 
  rename_gini() %>% 
  select(run = .run.number., step = .step., pubs.vs.data, agent.orientation, 
         rdm.cost, gini_grants:data.sharers.within.group.groups.with..publication.quantile....q.75.100...)

custom_scale <- scale_colour_viridis_d(begin = .1, end = .9, alpha = .5, 
                                       option = "C")
```


# Number of sharing agents
```{r data-sharers-overview-myopic, fig.height=6, fig.width=9}
df_clean %>% 
  filter(agent.orientation == "all-myopic") %>% 
  ggplot(aes(step, count.groups.with..data.sharing.., group = run)) +
  geom_line(alpha = .4) +
  facet_grid(rows = vars(pubs.vs.data),
             cols = vars(rdm.cost))
```

```{r data-sharers-overview-long-term, fig.height=6, fig.width=9}
df_clean %>% 
  filter(agent.orientation == "all-long-term") %>% 
  ggplot(aes(step, count.groups.with..data.sharing.., group = run)) +
  geom_line(alpha = .4) +
  facet_grid(rows = vars(pubs.vs.data),
             cols = vars(rdm.cost))
```

```{r data-sharers-smooth-myopic, fig.height=9, fig.width=7}
df_clean %>% 
  filter(agent.orientation == "all-myopic") %>% 
  ggplot(aes(step, count.groups.with..data.sharing.., 
             colour = factor(rdm.cost))) +
  geom_smooth() +
  custom_scale +
  facet_wrap(vars(pubs.vs.data), nrow = 3) +
  theme(legend.position = "top") +
  labs(y = "% of groups currently sharing data",
       colour = "cost penalty for sharing data")
```

```{r data-sharers-smooth-longterm, fig.height=9, fig.width=7}
df_clean %>% 
  filter(agent.orientation == "all-long-term") %>% 
  ggplot(aes(step, count.groups.with..data.sharing.., 
             colour = factor(rdm.cost))) +
  geom_smooth() +
  custom_scale +
  facet_wrap(vars(pubs.vs.data), nrow = 3) +
  theme(legend.position = "top") +
  labs(y = "% of groups currently sharing data",
       colour = "cost penalty for sharing data")
```

```{r data-sharers-smooth-combined, fig.height=6, fig.width=9}
df_clean %>% 
  ggplot(aes(step, count.groups.with..data.sharing.., 
             colour = factor(agent.orientation))) +
  geom_smooth() +
  facet_grid(rows = vars(pubs.vs.data),
             cols = vars(rdm.cost)) +
  custom_scale +
  theme(legend.position = "top") +
  labs(y = "% of groups currently sharing data",
       colour = "Agent orientation")
```

# Datasets shared
```{r data-sets-smooth-myopic, fig.height=9, fig.width=7}
df_clean %>% 
  filter(agent.orientation == "all-myopic") %>% 
  ggplot(aes(step, count.datasets, 
             colour = factor(rdm.cost))) +
  geom_smooth() +
  custom_scale +
  facet_wrap(vars(pubs.vs.data), nrow = 3) +
  theme(legend.position = "top") +
  labs(y = "# of available datasets",
       colour = "cost penalty for sharing data")
```
```{r data-sets-smooth-longterm, fig.height=9, fig.width=7}
df_clean %>% 
  filter(agent.orientation == "all-long-term") %>% 
  ggplot(aes(step, count.datasets, 
             colour = factor(rdm.cost))) +
  geom_smooth() +
  custom_scale +
  facet_wrap(vars(pubs.vs.data), nrow = 3) +
  theme(legend.position = "top") +
  labs(y = "# of available datasets",
       colour = "cost penalty for sharing data")
```
```{r data-sets-smooth-combined, fig.height=6, fig.width=9}
df_clean %>% 
  ggplot(aes(step, count.datasets, 
             colour = factor(agent.orientation))) +
  geom_smooth() +
  facet_grid(rows = vars(pubs.vs.data),
             cols = vars(rdm.cost)) +
  custom_scale +
  theme(legend.position = "top") +
  labs(y = "# of available datasets",
       colour = "Agent orientation")
```

```{r datasets-smooth-combined-emnd, fig.height=6, fig.width=10}
df_clean %>% 
  filter(step == 500) %>% 
  mutate(`Publication weight (vs. data)` = factor(
    pubs.vs.data, levels = c(.8, .9, 1), labels = scales::percent(c(.8, .9, 1)))
  ) %>% 
  ggplot(aes(factor(rdm.cost), sum..total.datasets..of.groups)) +
  geom_boxplot(aes(fill = agent.orientation), notch = TRUE) +
  geom_jitter(aes(group = agent.orientation), alpha = .2, 
              position = position_dodge(width = .8)) +
  facet_wrap(vars(`Publication weight (vs. data)`), labeller = label_both) +
  scale_fill_viridis_d(begin = .1, end = .9, alpha = .5, option = "C") +
  scale_y_continuous(labels = scales::comma) +
  theme(legend.position = "top") +
  labs(y = "# of total datasets",
       x = "Cost factor of data sharing",
       colour = "Agent orientation")
```

# Publications produced
```{r publications-smooth-combined, fig.height=6, fig.width=9}
# the whole plot is not very interesting: there is simply different levels of
# publication under individual learning. state this in the text
df %>% 
  mutate(`Publication weight (vs. data)` = factor(
    pubs.vs.data, levels = c(.8, .9, 1), labels = scales::percent(c(.8, .9, 1)))
  ) %>% 
  ggplot(aes(.step., sum..n.pubs.this.round..of.groups,
             colour = factor(agent.orientation))) +
  geom_smooth() + # make two smooths, one at 0-100, one at 100-500
  facet_grid(rows = vars(pubs.vs.data),
             cols = vars(rdm.cost)) +
  custom_scale +
  theme(legend.position = "top") +
  labs(y = "# of publications per round",
       colour = "Agent orientation")
```


```{r publications-end, fig.height=6, fig.width=10}
df_clean %>% 
  filter(step == 500) %>% 
    mutate(`Publication weight (vs. data)` = factor(
    pubs.vs.data, levels = c(.8, .9, 1), labels = scales::percent(c(.8, .9, 1)))
  ) %>% 
  ggplot(aes(factor(rdm.cost), sum..total.primary.publications..of.groups)) +
  geom_boxplot(aes(fill = agent.orientation), notch = TRUE) +
  geom_jitter(aes(group = agent.orientation), alpha = .2, 
              position = position_dodge(width = .8)) +
  facet_wrap(vars(`Publication weight (vs. data)`), labeller = label_both) +
  scale_fill_viridis_d(begin = .1, end = .9, alpha = .5, option = "C") +
  scale_y_continuous(labels = scales::comma) +
  theme(legend.position = "top") +
  labs(y = "# of total publications",
       x = "Cost factor of data sharing",
       colour = "Agent orientation")
```

# Inequalities
```{r}
# here it would be nice to compare to the standard path derived from the baseline
pdata <- df_clean %>% 
  select(run, step, pubs.vs.data, agent.orientation, rdm.cost,
         contains("gini")) %>% 
  pivot_longer(contains("gini")) %>% 
  mutate(name = str_remove(name, "gini_") %>% str_to_title()) %>% 
  filter(!is.na(value))
```


```{r ginis-myopics, fig.width=9, fig.height=9}
pdata %>% 
  filter(agent.orientation == "all-myopic") %>% 
  ggplot(aes(step, value, colour = factor(rdm.cost))) +
  geom_smooth() +
  facet_grid(cols = vars(name),
             rows = vars(factor(pubs.vs.data))) +
  scale_colour_viridis_d(option = "C", alpha = .5, begin = .1, end = .9) +
  labs(colour = "Cost factor of data sharing", y = "Gini index") +
  theme(legend.position = "top")
```

```{r ginis-longterms, fig.width=9, fig.height=9}
pdata %>% 
  filter(agent.orientation == "all-long-term") %>% 
  ggplot(aes(step, value, colour = factor(rdm.cost))) +
  geom_smooth() +
  facet_grid(cols = vars(name),
             rows = vars(factor(pubs.vs.data))) +
  scale_colour_viridis_d(option = "C", alpha = .5, begin = .1, end = .9) +
  labs(colour = "Cost factor of data sharing", y = "Gini index") +
  theme(legend.position = "top")
```

# Impact on individual groups
## Numbers of datasets

```{r}
df_data_means <- df_clean %>% 
  select(run, step, pubs.vs.data, agent.orientation, rdm.cost,
         starts_with("mean")) %>% 
  pivot_longer(contains("mean"),
               names_to = "quantile", names_pattern = "(q\\d)",
               values_to = "mean_datasets", 
               values_transform = list("mean_datasets" = as.numeric))
```
```{r}
display_quantity <- function(df, quantity, orientation = "all-long-term") {
  df %>% 
    filter(agent.orientation == orientation) %>% 
    ggplot(aes(step, {{quantity}}, colour = quantile)) +
    geom_smooth() +
      facet_grid(rows = vars(pubs.vs.data),
               cols = vars(rdm.cost)) +
    custom_scale
}
```


```{r shared-data-by-quantile-long-term, fig.height=6, fig.width=9}
df_data_means %>% 
  display_quantity(mean_datasets)
```

```{r shared-data-by-quantile-myopic, fig.height=6, fig.width=9}
df_data_means %>% 
  display_quantity(mean_datasets, "all-myopic")
```

## Number of sharers
```{r}
df_data_sharers <- df_clean %>% 
  select(run, step, pubs.vs.data, agent.orientation, rdm.cost,
         starts_with("data")) %>% 
  pivot_longer(starts_with("data"),
               names_to = "quantile", names_pattern = "(q\\..*?)\\.\\.\\.",
               values_to = "share_of_sharers", 
               values_transform = list("share_of_sharers" = as.numeric))
```

```{r sharers-by-quantile-long-term, fig.height=6, fig.width=9}
df_data_sharers %>% 
  display_quantity(share_of_sharers)
```

```{r sharers-by-quantile-myopic, fig.height=6, fig.width=9}
df_data_sharers %>% 
  display_quantity(share_of_sharers, "all-myopic")
```

