---
title: "Funding mechanisms"
author: "Thomas Klebel"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    keep_md: true
---

```{r setup, include=FALSE}
library(tidyverse)
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, dpi = 300)

theme_set(hrbrthemes::theme_ipsum_rc(base_family = "Hind"))
extrafont::loadfonts(device = "win")

df <- targets::tar_read(funding_mechanism)

df_clean <- df %>% 
  select(.run.number., .step., pubs.vs.data, 
          grants.gini:sum..total.datasets..of.groups)
```


# Ginis
```{r ginis}
df_clean %>% 
  pivot_longer(contains("gini")) %>% 
  ggplot(aes(.step., value, colour = pubs.vs.data, group = pubs.vs.data)) +
  geom_smooth() +
  facet_wrap(vars(name), nrow = 2, scales = "free_y")
```

```{r gini-groups}
df_clean %>% 
  mutate(across(pubs.vs.data, cut, breaks = c(0, .25, .5, .75, 1),
                include.lowest = TRUE)) %>% 
  pivot_longer(contains("gini")) %>% 
  ggplot(aes(.step., value, colour = pubs.vs.data, group = pubs.vs.data)) +
  geom_smooth() +
  facet_wrap(vars(name), nrow = 2, scales = "free_y")
```


# Number of publications
```{r publications}
df_clean %>% 
  ggplot(aes(.step., sum..total.primary.publications..of.groups,
             colour = pubs.vs.data, group = pubs.vs.data)) +
  geom_smooth()
```

```{r publications-end}
df_clean %>% 
  filter(.step. == 500) %>% 
  ggplot(aes(factor(pubs.vs.data), sum..total.primary.publications..of.groups)) +
  geom_boxplot(notch = TRUE)
```


# Number of datasets
```{r datasets}
df_clean %>% 
  filter(.step. == 500) %>% 
  ggplot(aes(factor(pubs.vs.data), sum..total.datasets..of.groups)) +
  geom_boxplot(notch = TRUE)
```