---
title: "Reuse"
author: "Thomas Klebel"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    keep_md: true
---

```{r setup, include=FALSE}
library(tidyverse)
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, dpi = 300)

theme_set(hrbrthemes::theme_ipsum_rc(base_family = "Hind"))
extrafont::loadfonts(device = "win")

df <- targets::tar_read(reuse)

df_clean <- df %>% 
  select(run = .run.number., step = .step., reuser.share,
         grants.gini:sum..total.datasets..of.groups)
```


# Numbers of datasets and publications
```{r}
df_clean %>% 
  select(run, step, reuser.share, contains("sum")) %>% 
  pivot_longer(contains("sum")) %>% 
  # remove data publications here, since with reuser.share=0, there is a straight
  # line at 0, which breaks the smoothing algorithm.
  filter(!str_detect(name, "data\\.publication")) %>% 
  ggplot(aes(step, value, colour = factor(reuser.share))) +
  geom_smooth() +
  facet_wrap(vars(name), nrow = 2, scales = "free_y")
```

```{r}
df_clean %>% 
  select(run, step, reuser.share, contains("data.publications")) %>% 
  ggplot(aes(step, sum..total.data.publications..of.groups, 
             colour = factor(reuser.share),
             group = run)) +
  geom_line(alpha = .5) +
  scale_colour_viridis_d(option = "C", begin = .1, end = .9, alpha = .5)
```

